name: The Safari Group
favicon: null
layout_spectrum: 0.9006758178584278
typography_spectrum: 1
title: Create inspire educate
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#564035'
    - '#e6dc49'
    - '#bc0809'
    - '#9e9e73'
  brandStrength: 0.75
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.6726708132773638
purpose: []
